/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoadTodoRouteImport } from './routes/load-todo/route'
import { Route as IndexImport } from './routes/index'
import { Route as LoadTodoIndexImport } from './routes/load-todo/index'
import { Route as LoadTodoShowTodoRouteImport } from './routes/load-todo/show-todo/route'
import { Route as LoadTodoOtherPathRouteImport } from './routes/load-todo/other-path/route'
import { Route as LoadTodoShowTodoIndexImport } from './routes/load-todo/show-todo/index'
import { Route as LoadTodoOtherPathIndexImport } from './routes/load-todo/other-path/index'

// Create/Update Routes

const LoadTodoRouteRoute = LoadTodoRouteImport.update({
  path: '/load-todo',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LoadTodoIndexRoute = LoadTodoIndexImport.update({
  path: '/',
  getParentRoute: () => LoadTodoRouteRoute,
} as any)

const LoadTodoShowTodoRouteRoute = LoadTodoShowTodoRouteImport.update({
  path: '/show-todo',
  getParentRoute: () => LoadTodoRouteRoute,
} as any)

const LoadTodoOtherPathRouteRoute = LoadTodoOtherPathRouteImport.update({
  path: '/other-path',
  getParentRoute: () => LoadTodoRouteRoute,
} as any)

const LoadTodoShowTodoIndexRoute = LoadTodoShowTodoIndexImport.update({
  path: '/',
  getParentRoute: () => LoadTodoShowTodoRouteRoute,
} as any)

const LoadTodoOtherPathIndexRoute = LoadTodoOtherPathIndexImport.update({
  path: '/',
  getParentRoute: () => LoadTodoOtherPathRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/load-todo': {
      preLoaderRoute: typeof LoadTodoRouteImport
      parentRoute: typeof rootRoute
    }
    '/load-todo/other-path': {
      preLoaderRoute: typeof LoadTodoOtherPathRouteImport
      parentRoute: typeof LoadTodoRouteImport
    }
    '/load-todo/show-todo': {
      preLoaderRoute: typeof LoadTodoShowTodoRouteImport
      parentRoute: typeof LoadTodoRouteImport
    }
    '/load-todo/': {
      preLoaderRoute: typeof LoadTodoIndexImport
      parentRoute: typeof LoadTodoRouteImport
    }
    '/load-todo/other-path/': {
      preLoaderRoute: typeof LoadTodoOtherPathIndexImport
      parentRoute: typeof LoadTodoOtherPathRouteImport
    }
    '/load-todo/show-todo/': {
      preLoaderRoute: typeof LoadTodoShowTodoIndexImport
      parentRoute: typeof LoadTodoShowTodoRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LoadTodoRouteRoute.addChildren([
    LoadTodoOtherPathRouteRoute.addChildren([LoadTodoOtherPathIndexRoute]),
    LoadTodoShowTodoRouteRoute.addChildren([LoadTodoShowTodoIndexRoute]),
    LoadTodoIndexRoute,
  ]),
])

/* prettier-ignore-end */
